EMPTY_START db 65
    db 84
    db 50
    db 48
    dw EMPTY_ARPEGGIOTABLE
    dw EMPTY_ARPEGGIOTABLE
    dw EMPTY_ARPEGGIOTABLE
    dw EMPTY_EFFECTBLOCKTABLE
    dw EMPTY_SUBSONG0_START
EMPTY_ARPEGGIOTABLE
EMPTY_PITCHTABLE
EMPTY_INSTRUMENTTABLE dw EMPTY_EMPTYINSTRUMENT
EMPTY_EMPTYINSTRUMENT db 0
EMPTY_EMPTYINSTRUMENT_LOOP db 0
    db 6
EMPTY_EFFECTBLOCKTABLE dw EMPTY_EFFECTBLOCK_P4P15
EMPTY_EFFECTBLOCK_P4P15 db 4
    db 15
EMPTY_SUBSONG0_START db 2
    db 1
    db 1
    db 0
    db 0
    db 6
    db 0
EMPTY_SUBSONG0_LINKER
EMPTY_SUBSONG0_LINKER_LOOP dw EMPTY_SUBSONG0_TRACK0
    dw EMPTY_SUBSONG0_TRACK1
    dw EMPTY_SUBSONG0_TRACK1
    dw EMPTY_SUBSONG0_LINKERBLOCK0
    db 0
    db 0
    dw EMPTY_SUBSONG0_LINKER
EMPTY_SUBSONG0_LINKERBLOCK0 db 64
    db 0
    db 0
    db 0
    dw EMPTY_SUBSONG0_SPEEDTRACK0
    dw EMPTY_SUBSONG0_EVENTTRACK0
EMPTY_SUBSONG0_TRACK0 db 124
    db 0
    db 61
    db 127
EMPTY_SUBSONG0_TRACK1 db 61
    db 127
EMPTY_SUBSONG0_SPEEDTRACK0 db 255
EMPTY_SUBSONG0_EVENTTRACK0 db 255